version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: pajat_dev
    environment:
      DB_USERNAME: dev
      DB_PASSWORD: dev
      DB_PORT: 5432
      DB_HOST: db
      DB_DATABASE: pajat
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: pajat_dev
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: pajat
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: pajat_db
  adminer:
    image: adminer:4.7.5
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 5051:8080 # http://localhost:5051/?pgsql=db&username=dev&db=pajat&ns=public
    container_name: pajat_adminer

volumes:
  pg_data: