name: Release

on:
  push:
    branches:
      - master

jobs:
  dockerhub-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toska/pajat2:latest
          build-args: |
            BASE_PATH=/pajat2
            GIT_SHA=${{ github.sha }}
